name: weather_pro
description: A weather app with a loading screen splash page.

# Flutter version setup (ensure your Flutter version is compatible)
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add any additional packages you may need later
  # e.g., for HTTP requests or state management.

dev_dependencies:
  flutter_test:
    sdk: flutter

# To use the material icons font, include this line
flutter:
  uses-material-design: true

  # Declare your assets, like images, here
  assets:
    - assets/logo.png  # Replace this with your actual logo file

  # You can add more assets like backgrounds or additional icons
  # e.g. - assets/splash_background.png
