name: weather_pro
description: A weather app with a loading screen splash page.

# Flutter version setup (ensure your Flutter version is compatible)
environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  provider:
  lottie: ^1.2.1


  dio: ^5.7.0
  intl: ^0.17.0
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  syncfusion_flutter_charts: ^21.2.4

  flutter_bloc: ^8.1.6
  permission_handler: ^11.1.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.4
  equatable: ^2.0.5
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2



  # Add any additional packages you may need later
  # e.g., for HTTP requests or state management.

dev_dependencies:
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"



  flutter_test:
    sdk: flutter

# To use the material icons font, include this line
flutter:
  uses-material-design: true

  # Declare your assets, like images, here
  assets:
    - assets/images/
    - assets/anims/
  # Replace this with your actual logo file

  # You can add more assets like backgrounds or additional icons
  # e.g. - assets/splash_background.png
